name: pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        pipeline
        npm install

    - name: Build
      run: |
        pipeline
        npm run build

    - name: Test
      run: |
        pipeline
        npm test

    - name: Deploy
      run: |
        pipeline
        echo "Deploying to production..."
        # Add your actual deployment commands here
